spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          enabled: true


gateway:
  cloud:
    routes:
      - id: xx-service
        uri: https://xx-url
        order: 100
        predicates:
          - Path=/xx-service/**
        filters:
          - RewritePath=/(?<segment>.*), /$\{segment}
      - id: yy-service
        uri: https://yy-url
        order: 101
        predicates:
          - Path=/yy-service/**
        filters:
          - RewritePath=/(?<segment>.*), /$\{segment}

debug:
  enabled: ${DEBUG_ENABLE:true}
  maingateway: ${GATEWAY_URL:http://testUrl:8081}
  cloud:
    applications: ##id ler eslesmelidir
      - id: xx-service
        uri: http://localhost:8085

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

server:
  max-http-header-size: 80KB
  port: 8081
  netty:
    max-initial-line-length: 20MB
    connection-timeout: 600

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
